# Site settings
title: Arun Arumugam
email: 
description: "I help machines!"
baseurl: ""
url: "https://arun477.github.io/arun/"
github_username:  arun477

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge