# Site settings
title: Arun Arumugam
email: arunarumugam411@gmail.com
description: "I help machines!"
baseurl: "https://arun477.github.io"
url: "https://arun477.github.io"
github_username:  arun477

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge